name: Install walletless node

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Set Voi environment variables
    env:
      VOINETWORK_SKIP_WALLET_SETUP: 1
      VOINETWORK_HEADLESS_INSTALL: 1
      VOINETWORK_DOCKER_SWARM_INIT_SETTINGS: "--advertise-addr 127.0.0.1"

    steps:
      - uses: actions/checkout@v3

      # Run install.sh script with environment variables set above
      - name: Run install.sh
        run: ./install.sh

      # Run goal command to verify service is running
      - name: Run goal command
        run: |
          container_id=$(docker ps -q -f name=voinetwork_algod)
          docker exec "${container_id}" bash -c "/node/bin/goal node status"

      - name: Validate auto-update is set and that scheduler can start
        run: |
          last_log_line=$(docker service logs voinetwork_scheduler | tail -n 1)
          if [[ "$last_log_line" != *"Add cronjob with schedule"* ]]; then
            echo "Scheduler logs do not contain the expected message:"
            echo ${last_log_line}
            exit 1
          fi
